apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: hello-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: HelloWorld is the Schema for the helloworlds API
      displayName: Hello World
      kind: HelloWorld
      name: helloworlds.hello.org.demo
      version: v1
  description: test
  displayName: helloworld
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - helloworld
  links:
  - name: Hello Operator
    url: https://hello-operator.domain
  maturity: alpha
  provider:
    name: jude
  version: 0.0.0
